# World Cup Prediction

I currently don't have a model at the moment so am thumb-sucking results with my very limited knowledge of football.

---
current work in progress, whilst we get out db up to date and accurate

In [69]:
import pandas as pd

In [91]:
wc_teams = ['Russia', 'Saudi Arabia', 'Egypt', 'Uruguay', 'Portugal', 'Spain',
       'Morocco', 'Iran', 'France', 'Australia', 'Peru', 'Denmark',
       'Argentina', 'Iceland', 'Croatia', 'Nigeria', 'Brazil',
       'Switzerland', 'Costa Rica', 'Serbia', 'Germany', 'Mexico',
       'Sweden', 'Korea', 'Belgium', 'Panama', 'Tunisia', 'England',
       'Poland', 'Senegal', 'Columbia', 'Japan']

In [92]:
players = pd.read_csv("CompleteDataset.csv", low_memory=False)

In [93]:
players.drop(['Unnamed: 0','Photo', 'Flag', 'Club Logo'], axis=1, inplace=True)

In [51]:
# figure out!!
#players.apply(pd.to_numeric, errors='ignore')

In [94]:
# only need players that are in WC
wc_players = players[players.Nationality.isin(wc_teams)]

In [95]:
wc_players.head()

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Acceleration,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,Cristiano Ronaldo,32,Portugal,94,94,Real Madrid CF,€95.5M,€565K,2228,89,...,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
1,L. Messi,30,Argentina,93,93,FC Barcelona,€105M,€565K,2154,92,...,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,88.0
2,Neymar,25,Brazil,92,94,Paris Saint-Germain,€123M,€280K,2100,94,...,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,84.0
3,L. Suárez,30,Uruguay,92,92,FC Barcelona,€97M,€510K,2291,88,...,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
4,M. Neuer,31,Germany,92,92,FC Bayern Munich,€61M,€230K,1493,58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
# need the mean of other stats
teams = wc_players.groupby('Nationality')['Overall', 'Age'].mean()

In [97]:
teams.index.names = ['Team']

In [58]:
teams.sort_values('Overall', ascending=False)

                Overall        Age
Team
Brazil        70.895320  27.208128
Portugal      70.599455  25.261580
Serbia        70.443609  25.413534
Egypt         69.968750  27.250000
Spain         69.939156  25.211973
Costa Rica    69.655172  26.344828
Morocco       69.653846  24.769231
Uruguay       69.477124  26.124183
Croatia       69.073394  24.981651
Peru          68.733333  25.966667
Iran          68.411765  24.882353
Senegal       68.302326  25.046512
Belgium       68.095588  23.893382
Tunisia       68.064516  27.161290
Argentina     67.765803  25.932642
France        67.286299  24.634969
Nigeria       66.761905  23.420635
Russia        66.470588  25.232026
Iceland       66.094340  25.679245
Germany       65.900877  24.202632
Panama        65.687500  25.812500
Mexico        65.647222  24.927778
Sweden        64.510870  25.119565
Poland        64.056380  25.231454
Switzerland   63.828326  24.055794
Denmark       63.309249  24.364162
England       63.069939  23.919632
Australia     62.757709  24.312775
Japan         62.272921  26.565032
Saudi Arabia  61.088146  25.252280

In [99]:
wc2018 = pd.read_csv('World Cup 2018_Dataset.csv')
wc2018.head()

,Team,Group,Previous appearances,Previous titles,Previous finals,Previous semifinals,Current FIFA rank,First match against,Match index,history with first opponent W-L,history with first opponent goals,Second match against,Match index.1,history with second opponent W-L,history with second opponent goals,Third match against,Match index.2,history with third opponent W-L,history with third opponent goals,Unnamed: 19
0,Russia,A,10.0,0.0,0.0,1.0,65.0,Saudi Arabia,1.0,-1.0,-2.0,Egypt,17.0,NaN,NaN,Uruguay,33.0,0.0,0.0,NaN
1,Saudi Arabia,A,4.0,0.0,0.0,0.0,63.0,Russia,1.0,1.0,2.0,Uruguay,18.0,1.0,1.0,Egypt,34.0,-5.0,-5.0,NaN
2,Egypt,A,2.0,0.0,0.0,0.0,31.0,Uruguay,2.0,-1.0,-2.0,Russia,17.0,NaN,NaN,Saudi Arabia,34.0,5.0,5.0,NaN
3,Uruguay,A,12.0,2.0,2.0,5.0,21.0,Egypt,2.0,1.0,2.0,Saudi Arabia,18.0,-1.0,-1.0,Russia,33.0,0.0,0.0,NaN
4,Porugal,B,6.0,0.0,0.0,2.0,3.0,Spain,3.0,-12.0,-31.0,Morocco,19.0,-1.0,-2.0,Iran,35.0,2.0,5.0,NaN

In [100]:
teams_wc_hist = wc2018[['Team','Previous \nappearances', 'Previous \ntitles', 'Previous\n finals', 
                        'Previous\n semifinals', 'Current \nFIFA rank']]

In [101]:
teams_wc_hist.dropna()

,Team,Previous appearances,Previous titles,Previous finals,Previous semifinals,Current FIFA rank
0,Russia,10.0,0.0,0.0,1.0,65.0
1,Saudi Arabia,4.0,0.0,0.0,0.0,63.0
2,Egypt,2.0,0.0,0.0,0.0,31.0
3,Uruguay,12.0,2.0,2.0,5.0,21.0
4,Porugal,6.0,0.0,0.0,2.0,3.0
5,Spain,14.0,1.0,1.0,2.0,6.0
6,Morocco,4.0,0.0,0.0,0.0,40.0
7,IRAN,4.0,0.0,0.0,0.0,32.0
8,France,14.0,1.0,2.0,5.0,9.0
9,Australia,4.0,0.0,0.0,0.0,39.0
10,Peru,4.0,0.0,0.0,0.0,11.0
11,Denmark,4.0,0.0,0.0,0.0,12.0
12,Argentina,16.0,2.0,5.0,5.0,4.0
13,Iceland,0.0,0.0,0.0,0.0,22.0
14,Croatia,4.0,0.0,0.0,1.0,17.0
15,Nigeria,5.0,0.0,0.0,0.0,50.0
16,Brazil,20.0,5.0,7.0,11.0,2.0
17,Switzerland,10.0,0.0,0.0,0.0,8.0
18,Costarica,4.0,0.0,0.0,0.0,26.0
19,Serbia,11.0,0.0,0.0,2.0,37.0
20,Germany,18.0,4.0,8.0,13.0,1.0
21,Mexico,15.0,0.0,0.0,0.0,16.0
22,Sweden,11.0,0.0,1.0,4.0,18.0
23,Korea,9.0,0.0,0.0,1.0,59.0
24,Belgium,12.0,0.0,0.0,1.0,5.0
25,Panama,0.0,0.0,0.0,0.0,56.0
26,Tunisia,4.0,0.0,0.0,0.0,27.0
27,England,14.0,1.0,1.0,2.0,15.0
28,Poland,7.0,0.0,0.0,2.0,7.0
29,Senegal,1.0,0.0,0.0,0.0,23.0
30,Columbia,5.0,0.0,0.0,0.0,13.0
31,Japan,5.0,0.0,0.0,0.0,55.0

In [107]:
teams_wc_hist.replace({'Porugal': 'Portugal', 'IRAN': 'Iran', 'Costarica': 'Costa Rica'}, inplace=True)

/Users/wahe3bru/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3836: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  limit=limit, regex=regex)

In [108]:
teams_wc_hist.set_index('Team')

,Previous appearances,Previous titles,Previous finals,Previous semifinals,Current FIFA rank
Team,,,,,
Russia,10.0,0.0,0.0,1.0,65.0
Saudi Arabia,4.0,0.0,0.0,0.0,63.0
Egypt,2.0,0.0,0.0,0.0,31.0
Uruguay,12.0,2.0,2.0,5.0,21.0
Portugal,6.0,0.0,0.0,2.0,3.0
Spain,14.0,1.0,1.0,2.0,6.0
Morocco,4.0,0.0,0.0,0.0,40.0
Iran,4.0,0.0,0.0,0.0,32.0
France,14.0,1.0,2.0,5.0,9.0
Australia,4.0,0.0,0.0,0.0,39.0
Peru,4.0,0.0,0.0,0.0,11.0
Denmark,4.0,0.0,0.0,0.0,12.0
Argentina,16.0,2.0,5.0,5.0,4.0
Iceland,0.0,0.0,0.0,0.0,22.0
Croatia,4.0,0.0,0.0,1.0,17.0
Nigeria,5.0,0.0,0.0,0.0,50.0
Brazil,20.0,5.0,7.0,11.0,2.0
Switzerland,10.0,0.0,0.0,0.0,8.0
Costa Rica,4.0,0.0,0.0,0.0,26.0
Serbia,11.0,0.0,0.0,2.0,37.0
Germany,18.0,4.0,8.0,13.0,1.0
Mexico,15.0,0.0,0.0,0.0,16.0
Sweden,11.0,0.0,1.0,4.0,18.0
Korea,9.0,0.0,0.0,1.0,59.0
Belgium,12.0,0.0,0.0,1.0,5.0
Panama,0.0,0.0,0.0,0.0,56.0
Tunisia,4.0,0.0,0.0,0.0,27.0
England,14.0,1.0,1.0,2.0,15.0
Poland,7.0,0.0,0.0,2.0,7.0
Senegal,1.0,0.0,0.0,0.0,23.0
Columbia,5.0,0.0,0.0,0.0,13.0
Japan,5.0,0.0,0.0,0.0,55.0
NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
teams_fin = teams.join(teams_wc_hist.set_index('Team'))

In [262]:
teams_fin.rename(columns={'Overall':'Squad strength'}, inplace=True)

In [263]:
teams_fin

,Squad strength,Age,Previous appearances,Previous titles,Previous finals,Previous semifinals,Current FIFA rank
Team,,,,,,,
Argentina,67.765803,25.932642,16.0,2.0,5.0,5.0,4.0
Australia,62.757709,24.312775,4.0,0.0,0.0,0.0,39.0
Belgium,68.095588,23.893382,12.0,0.0,0.0,1.0,5.0
Brazil,70.895320,27.208128,20.0,5.0,7.0,11.0,2.0
Costa Rica,69.655172,26.344828,4.0,0.0,0.0,0.0,26.0
Croatia,69.073394,24.981651,4.0,0.0,0.0,1.0,17.0
Denmark,63.309249,24.364162,4.0,0.0,0.0,0.0,12.0
Egypt,69.968750,27.250000,2.0,0.0,0.0,0.0,31.0
England,63.069939,23.919632,14.0,1.0,1.0,2.0,15.0
France,67.286299,24.634969,14.0,1.0,2.0,5.0,9.0
Germany,65.900877,24.202632,18.0,4.0,8.0,13.0,1.0
Iceland,66.094340,25.679245,0.0,0.0,0.0,0.0,22.0
Iran,68.411765,24.882353,4.0,0.0,0.0,0.0,32.0
Japan,62.272921,26.565032,5.0,0.0,0.0,0.0,55.0
Mexico,65.647222,24.927778,15.0,0.0,0.0,0.0,16.0
Morocco,69.653846,24.769231,4.0,0.0,0.0,0.0,40.0
Nigeria,66.761905,23.420635,5.0,0.0,0.0,0.0,50.0
Panama,65.687500,25.812500,0.0,0.0,0.0,0.0,56.0
Peru,68.733333,25.966667,4.0,0.0,0.0,0.0,11.0
Poland,64.056380,25.231454,7.0,0.0,0.0,2.0,7.0
Portugal,70.599455,25.261580,6.0,0.0,0.0,2.0,3.0
Russia,66.470588,25.232026,10.0,0.0,0.0,1.0,65.0
Saudi Arabia,61.088146,25.252280,4.0,0.0,0.0,0.0,63.0
Senegal,68.302326,25.046512,1.0,0.0,0.0,0.0,23.0
Serbia,70.443609,25.413534,11.0,0.0,0.0,2.0,37.0
Spain,69.939156,25.211973,14.0,1.0,1.0,2.0,6.0
Sweden,64.510870,25.119565,11.0,0.0,1.0,4.0,18.0
Switzerland,63.828326,24.055794,10.0,0.0,0.0,0.0,8.0
Tunisia,68.064516,27.161290,4.0,0.0,0.0,0.0,27.0
Uruguay,69.477124,26.124183,12.0,2.0,2.0,5.0,21.0

---

### Connect to RDS

In [238]:
import psycopg2

/Users/wahe3bru/anaconda3/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [245]:
# Do not change
rds_endpoint = 'tsholomrdsinstanceext.cnzbp4ndrpos.eu-west-1.rds.amazonaws.com'
rds_user = 'tsholofelo_madi'
rds_psswrd = 'tsholoexe'
port = 5432
rds_database = 'FIFAWorldCup2018'

In [246]:
try:
    conn = psycopg2.connect("dbname='{:s}' user='{:s}' host='{:s}' password='{:s}'".format(rds_database, rds_user, rds_endpoint, rds_psswrd))
    print("Connected to the database")
except:
    print("Unable to connect to the database, please check your settings")

Connected to the database

In [259]:
Team_stat = pd.read_sql_query("SELECT long_name, overall_rating, att, mid, def FROM teams", con=conn)

In [260]:
Team_stat.rename(columns={'long_name':'Team'}, inplace=True)

In [264]:
teams_final = teams_fin.join(Team_stat.set_index('Team'))

In [265]:
teams_final

,Squad strength,Age,Previous appearances,Previous titles,Previous finals,Previous semifinals,Current FIFA rank,overall_rating,att,mid,def
Team,,,,,,,,,,,
Argentina,67.765803,25.932642,16.0,2.0,5.0,5.0,4.0,84.0,86.0,82.0,81.0
Australia,62.757709,24.312775,4.0,0.0,0.0,0.0,39.0,72.0,69.0,72.0,70.0
Belgium,68.095588,23.893382,12.0,0.0,0.0,1.0,5.0,83.0,85.0,83.0,83.0
Brazil,70.895320,27.208128,20.0,5.0,7.0,11.0,2.0,86.0,87.0,85.0,84.0
Costa Rica,69.655172,26.344828,4.0,0.0,0.0,0.0,26.0,73.0,69.0,73.0,73.0
Croatia,69.073394,24.981651,4.0,0.0,0.0,1.0,17.0,80.0,81.0,82.0,78.0
Denmark,63.309249,24.364162,4.0,0.0,0.0,0.0,12.0,78.0,76.0,79.0,76.0
Egypt,69.968750,27.250000,2.0,0.0,0.0,0.0,31.0,76.0,75.0,77.0,74.0
England,63.069939,23.919632,14.0,1.0,1.0,2.0,15.0,81.0,83.0,81.0,80.0
France,67.286299,24.634969,14.0,1.0,2.0,5.0,9.0,85.0,86.0,84.0,82.0
Germany,65.900877,24.202632,18.0,4.0,8.0,13.0,1.0,86.0,85.0,85.0,85.0
Iceland,66.094340,25.679245,0.0,0.0,0.0,0.0,22.0,75.0,75.0,78.0,74.0
Iran,68.411765,24.882353,4.0,0.0,0.0,0.0,32.0,NaN,NaN,NaN,NaN
Japan,62.272921,26.565032,5.0,0.0,0.0,0.0,55.0,75.0,76.0,78.0,73.0
Mexico,65.647222,24.927778,15.0,0.0,0.0,0.0,16.0,79.0,81.0,79.0,77.0
Morocco,69.653846,24.769231,4.0,0.0,0.0,0.0,40.0,76.0,74.0,77.0,77.0
Nigeria,66.761905,23.420635,5.0,0.0,0.0,0.0,50.0,75.0,75.0,76.0,72.0
Panama,65.687500,25.812500,0.0,0.0,0.0,0.0,56.0,69.0,68.0,69.0,69.0
Peru,68.733333,25.966667,4.0,0.0,0.0,0.0,11.0,76.0,78.0,75.0,74.0
Poland,64.056380,25.231454,7.0,0.0,0.0,2.0,7.0,80.0,83.0,79.0,78.0
Portugal,70.599455,25.261580,6.0,0.0,0.0,2.0,3.0,84.0,88.0,83.0,82.0
Russia,66.470588,25.232026,10.0,0.0,0.0,1.0,65.0,79.0,79.0,77.0,75.0
Saudi Arabia,61.088146,25.252280,4.0,0.0,0.0,0.0,63.0,72.0,71.0,72.0,71.0
Senegal,68.302326,25.046512,1.0,0.0,0.0,0.0,23.0,76.0,77.0,77.0,76.0
Serbia,70.443609,25.413534,11.0,0.0,0.0,2.0,37.0,78.0,76.0,81.0,78.0
Spain,69.939156,25.211973,14.0,1.0,1.0,2.0,6.0,85.0,84.0,86.0,85.0
Sweden,64.510870,25.119565,11.0,0.0,1.0,4.0,18.0,77.0,78.0,76.0,77.0
Switzerland,63.828326,24.055794,10.0,0.0,0.0,0.0,8.0,78.0,76.0,77.0,78.0
Tunisia,68.064516,27.161290,4.0,0.0,0.0,0.0,27.0,73.0,73.0,72.0,72.0
Uruguay,69.477124,26.124183,12.0,2.0,2.0,5.0,21.0,80.0,86.0,77.0,80.0